name: Test

on:
  push:
    branches:
    - main

jobs:
  my_job:
    runs-on: ubuntu-latest
    name: deploy to staging
    steps:
      - name: test
        run: |
          cd ../../
          chmod +x run.sh
          ./run.sh
    
