name: Test

on:
  push:
    branches:
    - main

jobs:
  my_job:
    runs-on: ubuntu-latest
    name: deploy to staging
    steps:
      - name: test
        run: |
          for i in {1..1000000}; do echo "line $i"; done
